openapi: 3.0.0
info:
  title: OpenAPI Sample Library
  description: Curated real-world API examples
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
components:
  schemas:
    GitHubUser:
      $ref: './components\github\schema\issue-update-request.yaml'
    StripePayment:
      $ref: './schemas/stripe/payment-schema.yaml'
    JiraIssue:
      $ref: './schemas/jira/issue-schema.yaml'
    NotionPage:
      $ref: './schemas/notion/page-schema.yaml'
    SlackMessage:
      $ref: './schemas/slack/message-schema.yaml'
paths:
  /github:
    $ref: './apis/github/paths.yaml'
  /stripe:
    $ref: './apis/stripe/paths.yaml'
  /jira:
    $ref: './apis/jira/paths.yaml'
  /notion:
    $ref: './apis/notion/paths.yaml'
  /slack:
    $ref: './apis/slack/paths.yaml'
