name: Welcome First-Time Contributors

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
      - name: Greet first-time contributor
        uses: actions/first-interaction@v1.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 Hello and welcome!  
            Thanks for opening your first issue. We’ll review and get back to you shortly.  
            Feel free to check out our [contributing guide](CONTRIBUTING.md) if you haven’t already.
          pr-message: |
            🎉 Thank you for your first pull request!  
            We really appreciate your contribution. The team will review it soon.  
            Meanwhile, feel free to explore other open issues or suggest improvements.
